//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogData
{
    using System;
    using System.Collections.Generic;
    
    public partial class CentroidCluster
    {
        public CentroidCluster()
        {
            this.CentroidClusters1 = new HashSet<CentroidCluster>();
            this.ClusteredBooks = new HashSet<ClusteredBook>();
        }
    
        public int Id { get; set; }
        public int CentroidId { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual ICollection<CentroidCluster> CentroidClusters1 { get; set; }
        public virtual CentroidCluster CentroidCluster1 { get; set; }
        public virtual Document Document { get; set; }
        public virtual ICollection<ClusteredBook> ClusteredBooks { get; set; }
    }
}
