//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClusterError
    {
        public int Id { get; set; }
        public int Iteration { get; set; }
        public int ClusterNumber { get; set; }
        public int OldCentriodId { get; set; }
        public int NewCentroidId { get; set; }
        public double Error { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Document Document1 { get; set; }
    }
}
