//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public Document()
        {
            this.CentroidClusters = new HashSet<CentroidCluster>();
            this.ClusteredBooks = new HashSet<ClusteredBook>();
            this.ClusterErrors = new HashSet<ClusterError>();
            this.ClusterErrors1 = new HashSet<ClusterError>();
            this.LastBookUpdates = new HashSet<LastBookUpdate>();
            this.LastBookUpdates1 = new HashSet<LastBookUpdate>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string AdditionalTitle { get; set; }
        public string Serial { get; set; }
        public string BBK { get; set; }
        public string Author { get; set; }
        public string Editor { get; set; }
        public string Publish { get; set; }
        public string City { get; set; }
        public string ImprintYear { get; set; }
        public Nullable<int> FirstYear { get; set; }
        public Nullable<int> LastYear { get; set; }
        public Nullable<int> PartNumber { get; set; }
        public string Part { get; set; }
        public string PartName { get; set; }
        public string Remark { get; set; }
        public string Illustrations { get; set; }
        public string Stuff { get; set; }
        public string Biblio { get; set; }
        public string ISBN { get; set; }
        public string ISSN { get; set; }
        public string LongFileName { get; set; }
        public string LocalCode { get; set; }
        public string LocalNumber { get; set; }
        public int DocumentTypeId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public long CreateDate { get; set; }
        public long UpdateDate { get; set; }
        public string Pages { get; set; }
        public string Edition { get; set; }
        public string Volume { get; set; }
        public string VolumeNumber { get; set; }
        public string ParentAuthor { get; set; }
        public string ParentPublish { get; set; }
        public string ParentEdition { get; set; }
        public string ParentEditor { get; set; }
        public string ParentAdditionalTitle { get; set; }
        public string ParentImprintYear { get; set; }
        public string ParentCity { get; set; }
        public string ParentTitle { get; set; }
        public string ParentVolumeName { get; set; }
        public string ParentPartName { get; set; }
        public string ParentVolume { get; set; }
        public string ParentPart { get; set; }
        public string SerialParal { get; set; }
        public string SerialAdditionalTitle { get; set; }
        public string SerialEditor { get; set; }
        public string SerialPart { get; set; }
        public string SerialPartName { get; set; }
        public string SerialNumber { get; set; }
        public string SerialISSN { get; set; }
        public Nullable<short> IsParent { get; set; }
        public string Annotation1 { get; set; }
        public string Annotation2 { get; set; }
        public string Annotation3 { get; set; }
        public string Annotation4 { get; set; }
        public string Annotation5 { get; set; }
        public string Annotation6 { get; set; }
        public string Annotation7 { get; set; }
        public string Annotation8 { get; set; }
        public string Annotation9 { get; set; }
        public string Annotation10 { get; set; }
        public string Annotation11 { get; set; }
        public string Annotation12 { get; set; }
        public string Annotation13 { get; set; }
        public string Annotation14 { get; set; }
        public string Annotation15 { get; set; }
        public string Annotation16 { get; set; }
    
        public virtual ICollection<CentroidCluster> CentroidClusters { get; set; }
        public virtual ICollection<ClusteredBook> ClusteredBooks { get; set; }
        public virtual ICollection<ClusterError> ClusterErrors { get; set; }
        public virtual ICollection<ClusterError> ClusterErrors1 { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual ICollection<LastBookUpdate> LastBookUpdates { get; set; }
        public virtual ICollection<LastBookUpdate> LastBookUpdates1 { get; set; }
    }
}
