//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogData
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastBookUpdate
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public System.DateTime Updated { get; set; }
        public int ComparedWithBookId { get; set; }
        public string LastSnippet { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Document Document1 { get; set; }
    }
}
