//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CatalogData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public Word()
        {
            this.WordsFrequencies = new HashSet<WordsFrequency>();
        }
    
        public int Id { get; set; }
        public string Word1 { get; set; }
    
        public virtual ICollection<WordsFrequency> WordsFrequencies { get; set; }
    }
}
